// <auto-generated />
using System;
using FlipStoreAnon.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlipChatAnon.Migrations
{
    [DbContext(typeof(FlipDbContext))]
    partial class FlipDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlipChatStore.ChatMessage", b =>
                {
                    b.Property<long>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("message_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MessageId"));

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("room_id");

                    b.Property<string>("SenderConnectionId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sender_connection_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("message_text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("MessageId");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_messages_room_id");

                    b.HasIndex("SenderConnectionId")
                        .HasDatabaseName("ix_messages_sender");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_messages_created_at");

                    b.HasIndex("RoomId", "Timestamp")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_messages_room_created");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("FlipChatStore.ChatRoom", b =>
                {
                    b.Property<string>("RoomId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("room_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("User1ConnectionId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user1_connection_id");

                    b.Property<string>("User2ConnectionId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user2_connection_id");

                    b.HasKey("RoomId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_chat_rooms_created_at");

                    b.HasIndex("User1ConnectionId")
                        .IsUnique()
                        .HasDatabaseName("ix_chat_rooms_user1_unique");

                    b.HasIndex("User2ConnectionId")
                        .IsUnique()
                        .HasDatabaseName("ix_chat_rooms_user2_unique");

                    b.ToTable("chat_rooms", (string)null);
                });

            modelBuilder.Entity("FlipChatStore.UserData", b =>
                {
                    b.Property<string>("ConnectionId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("connection_id");

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("age_group");

                    b.Property<string>("CompanionAge")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("preferred_age");

                    b.Property<string>("CompanionGender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("preferred_gender");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("gender");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("light")
                        .HasColumnName("theme");

                    b.HasKey("ConnectionId");

                    b.HasIndex("JoinedAt")
                        .HasDatabaseName("ix_user_sessions_joined_at");

                    b.HasIndex("CompanionGender", "CompanionAge")
                        .HasDatabaseName("ix_user_sessions_preferences");

                    b.HasIndex("Gender", "Age")
                        .HasDatabaseName("ix_user_sessions_gender_age");

                    b.ToTable("user_sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_sessions_age", "age_group IN ('under14', '15-17', '18plus')");

                            t.HasCheckConstraint("ck_user_sessions_gender", "gender IN ('male', 'female', 'other')");

                            t.HasCheckConstraint("ck_user_sessions_pref_age", "preferred_age IN ('under14', '15-17', '18plus')");

                            t.HasCheckConstraint("ck_user_sessions_pref_gender", "preferred_gender IN ('male', 'female', 'any')");

                            t.HasCheckConstraint("ck_user_sessions_theme", "theme IN ('light', 'dark')");
                        });
                });

            modelBuilder.Entity("FlipChatStore.ChatMessage", b =>
                {
                    b.HasOne("FlipChatStore.ChatRoom", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlipChatStore.UserData", "User")
                        .WithMany()
                        .HasForeignKey("SenderConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlipChatStore.ChatRoom", b =>
                {
                    b.HasOne("FlipChatStore.UserData", "User1")
                        .WithMany()
                        .HasForeignKey("User1ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlipChatStore.UserData", "User2")
                        .WithMany()
                        .HasForeignKey("User2ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User1");

                    b.Navigation("User2");
                });
#pragma warning restore 612, 618
        }
    }
}
